"""
Core data models for the Boom-Bust Sentinel system.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional, Union, Any


@dataclass
class MetricValue:
    """Represents a single metric measurement."""
    value: Union[float, int, str]
    timestamp: datetime
    confidence: float
    source: str
    metadata: Dict[str, Any]


@dataclass
class AlertThreshold:
    """Configuration for alert thresholds."""
    metric_name: str
    threshold_type: str  # 'absolute', 'percentage', 'standard_deviation'
    threshold_value: float
    comparison_period: int  # days
    enabled: bool


@dataclass
class DataSource:
    """Information about a data source."""
    name: str
    url: str
    update_frequency: str  # cron expression
    last_successful_update: Optional[datetime]
    health_status: str  # 'healthy', 'degraded', 'failed'
    retry_count: int


@dataclass
class Alert:
    """Represents an alert generated by the system."""
    id: str
    alert_type: str
    data_source: str
    metric_name: str
    current_value: MetricValue
    threshold: AlertThreshold
    message: str
    channels_sent: List[str]
    acknowledged: bool
    created_at: datetime


@dataclass
class ScraperResult:
    """Result from a scraper execution."""
    data_source: str
    metric_name: str
    success: bool
    data: Optional[Dict[str, Any]]
    error: Optional[str]
    execution_time: float
    timestamp: datetime